OrleansDashboard/DashboardModule.cs
When viewing a single silo statistics, if you picked a silo that was dead I would get unobserved exceptions.
`Exc level 2: Orleans.Runtime.OrleansException: The target silo is no longer active: target was S172.18.124.91:11111:191609335, but this silo is S172.18.124.91:11111:191708862. The rejected message is Request S172.18.124.91:11111:191708862*grn/7483D9D2/00000000@32f88da7->S172.18.124.91:11111:191609335SiloControl@S0000000c #9812: global::Orleans.ISiloControl:GetRuntimeStatistics().	`
=> prevent unobserved exception when getting statistics from a dead silo

OrleansDashboard/StatsPublisher.cs
We often get `NullReferenceException` from `StatsPublisher` on deployment when `Dashboard.OrleansScheduler` is `null`. Nothing really important, but better to be fixed I guess
=> Fix StatsPublisher error on silo shutdown

OrleansDashboard/DashboardCounters.cs, OrleansDashboard/DashboardGrain.cs, OrleansDashboard/ISiloDetailsProvider.cs, OrleansDashboard/OrleansDashboard.csproj, PerformanceTests/DashboardGrainBenchmark.cs
this PR contains a solution for #47 
I've added an ISiloDetailsProvider which is resolved from the runtime if it is provided.
Default behavior is to use the host details provided by IManagementGrain using the membershiptable.
=> Add ISiloDetailsProvider, allows for custom implementations & SF integration

OrleansDashboard/GrainProfiler.cs, TestGrains/TestMessageBasedGrain.cs, TestHost/Program.cs
Heads up from Orleankka!
For long time Orleankka users were missing such useful metric as requests\errors\latency per sec since the tracing was done against method name and as you know all grains generated by Orleankka have uniform api (i.e. singe `Receive` method.) and as a result all calls were aggregated under single label.
I've tried to make this integration non-intrusive and to have as less coupling as possible, so I've used the trick from .NET framework and did integration based on simple convention.
Hope it's alright. If you can propose better alternatives I'm ok to redo. Thanks!
=> Support for message-based grains (uniform api)

OrleansDashboard/GrainProfiler.cs, TestGrains/TestMessageBasedGrain.cs, TestHost/Program.cs
By binding to delegate signature instead of interface were are free from mutual coupling and do have best performance possible.
=> Use DI for custom method name formatting

App/reminders/reminders.jsx
Currently you either have to guess which is the last page, or press "Next" multiple times
This PR aims to fix that by adding a "Last" button which takes you to the last page.
Its based on the total count (which exists on the response), divided by 25.
Also, the "showNext" button wasn't calculated right, as it assumes that another page exists if there are 25, it is now calculated by totalPages > page
=> reminders - Feat/add go to last

App/components/reminder-table.jsx
Added input filters for each header
This solves (partially) the issue of many kinds of reminders, when we are only interested in one specific kind, or if we want to filter by primary key.
The only remaining issue here is that this is a "per-page" filter, since the server only returns 25.
May I ask why not return more? The data is relatively small, and shouldn't explode to huge proportions, either way 25 is a very small number to request from the server IMO.
=> reminders - add per-page search bar

PerformanceTests/DashboardGrainBenchmark.cs
...although the number is kind of relative, as it represents multiple add operations (one for each silo, of which there are 10).
```
Method | SiloCount | GrainTypeCount | GrainMethodCount | HistorySize |      Mean |      Error |      StdDev |
-------------------------------------- |---------- |--------------- |----------------- |------------ |----------:|-----------:|------------:|
Test_Add_TraceHistory |        10 |             50 |               10 |         100 | 936.34 ms | 58.0484 ms | 170.2459 ms |
Test_QueryAll_TraceHistory |        10 |             50 |               10 |         100 |  75.91 ms |  3.5889 ms |  10.0638 ms |
Test_QuerySilo_TraceHistory |        10 |             50 |               10 |         100 |  19.38 ms |  0.3832 ms |   0.3763 ms |
Test_QueryGrain_TraceHistory …
```
=> added benchmark for 'Add'

OrleansDashboard/DashboardCounters.cs, OrleansDashboard/DashboardGrain.cs, OrleansDashboard/DashboardMiddleware.cs, OrleansDashboard/DashboardRemindersGrain.cs, OrleansDashboard/DashboardTelemetryProducer.cs, OrleansDashboard/GrainProfiler.cs, OrleansDashboard/IDashboardGrain.cs, OrleansDashboard/IDashboardRemindersGrain.cs, OrleansDashboard/ISiloGrain.cs, OrleansDashboard/OrleansDashboard.csproj, OrleansDashboard/SiloGrain.cs
Almost most calls can be made with immutable parameters or responses. Have not changed GetCounters yet because it is a mutable object.
=> Make calls immutable.

OrleansDashboard/GrainProfiler.cs
The call is `[OneWay]` and hence will complete synchronously
=> Avoid blocking timer thread in GrainProfiler

OrleansDashboard/Dashboard.cs, OrleansDashboard/ServiceCollectionExtensions.cs, OrleansDashboard/SiloDispatcher.cs
- Avoid `static` for `SiloDispatcher.TaskScheduler`
- Share single dispatcher instance between silo container and ASP.NET container
- Pass `DenyChildAttach` to `Task.Factory.StartNew`
- Remove CancellationToken` from `Task.Factory.StartNew` (needless cost)
=> Minor SiloDispatcher cleanup

OrleansDashboard/Dashboard.cs, OrleansDashboard/DashboardOptions.cs, OrleansDashboard/OrleansDashboard.csproj, OrleansDashboard/ServiceCollectionExtensions.cs
In self host mode I require that there is a base path such as http://localhost:8000/dashboard.
I added a BasePath string property in DashboardOptions.
=> Allow setting a BasePath in self host mode like /dashboard

readme.md
Updated the readme to expand on enabling CPU/Memory metrics on the dashboard.  These metrics (at the time of writing) are Windows only, but ***are*** able to be used in .net core; previously it said original framework only.
=> Info on enabling CPU/Memory metrics.

readme.md
Fixed issue #225 and additionally adds use of `Microsoft.Orleans.OrleansTelemetryConsumers.Linux`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/orleanscontrib/orleansdashboard/226)
=> Updated config for grain discovery and linux cpu and memory metrics

Directory.Build.props, OrleansDashboard.Client/Model/GrainTraceEntry.cs, OrleansDashboard/Metrics/DashboardTelemetryConsumer.cs, OrleansDashboard/Metrics/GrainProfilerFilter.cs, OrleansDashboard/Metrics/Grains/DashboardGrain.cs, OrleansDashboard/Metrics/History/TraceHistory.cs
I made a memory test of my application and have seen this comparison to be one of the most allocating methods.
This PR fixes several problems:
1. The very inefficient equality checks in GrainTraceEntry.
2. Only update the counters and statistics if needed. There is actually no need to update them if nobody is interested to see them.
3. Allocations from reflection.
4. Allocations in the History from the list.
=> Fix allocations.

readme.md
I created an `IHostEnvironmentStatistics` implementation for AWS ECS, and I've been using it in production workloads for almost 9 months. It works for tasks running on both EC2 and Fargate.
I created the package initially to show some quick CPU/memory metrics on the Orleans Dashboard, and I thought others may be interested as well. This PR simply adds a note to the README.
=> Add link to IHostEnvironmentStatistics for AWS ECS

Tests/TestHosts/TestHost/index.min.js
Hi, 
In the spirit of Hacktoberfest I've given this a go. This will set the theme to the OS preference, but only if no theme preference has been saved to local storage.
I hope this is what you were after - let me know if you have any issues.
Cheers
James
=> fix #296 default color scheme based on OS preference

OrleansDashboard/DashboardMiddleware.cs, OrleansDashboard/DashboardOptions.cs, OrleansDashboard/Index.html
Closes #328 
This is one way of resolving #328 as it allows for the ability to load in a custom css file. I argue its a valid feature as it also enables more advanced scenarios such as replacing the logo and changing colors.
In order to try this out:
1. Create a simple css file like: 
```scss
// custom.css
* {
font-family: cursive !important;
}
```
2. Ensure that static assets are getting served by middleware
3. Configure orleans to serve this custom css file
```csharp
app.UseStaticFiles();
app.UseOrleansDashboard(new OrleansDashboard.DashboardOptions
{
CustomCssPath = "/custom.css"
});
```
=> Ability to include a custom css file

OrleansDashboard/Implementation/TraceWriter.cs
1/26/2022 3:45:57 PM fail: [  100005] Silo Caught an UnobservedTaskException event sent by [Id=1269, Status=Faulted]. Exception = 
Exc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.)
Exc level 1: System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.Stream.Write(ReadOnlySpan`1 buffer)
at …
=> Converting to WriteAsync to resolve exceptions

OrleansDashboard/Implementation/TraceWriter.cs
The private `Write` method - used by TraceListener - calls an async method but does not await or `Ignore()` the task, so any exceptions further down would bubble up and be uncaught, causing the app to crash.
This PR adds an `Ignore()` to the task so that any exceptions are handled - or rather, caught and ignored... and not bubbled up uncaught.
Also removed the unnecessary `ConfigureAwait` and `ContinueWith` calls, as we do not await the task anyway.
=> Ignore() any exceptions from the task in the sync Write method

Directory.Build.props, OrleansDashboard.Core/Model/StatCounter.cs, OrleansDashboard.Core/OrleansDashboard.Core.csproj, OrleansDashboard.EmbeddedAssets/OrleansDashboard.EmbeddedAssets.csproj, OrleansDashboard/BasicAuthMiddleware.cs, OrleansDashboard/OrleansDashboard.csproj, OrleansDashboard/ServiceCollectionExtensions.cs, OrleansDashboard/SiloGrainService.cs, Tests/PerformanceTests/PerformanceTests.csproj, Tests/TestGrains/TestGrains.csproj, Tests/TestHosts/TestHost/TestHost.csproj, Tests/TestHosts/TestHostCohosted2/TestHostCohosted2.csproj, Tests/TestHosts/TestHostSeparate/TestHostSeparate.csproj, Tests/UnitTests/UnitTests.csproj
Upgrades to .NET 8.0 / Orleans 8.0 and bumps version to align
=> Upgrade to .NET 8.0

Directory.Build.props, OrleansDashboard/Implementation/Grains/DashboardGrain.cs, OrleansDashboard/OrleansDashboard.csproj, Tests/PerformanceTests/PerformanceTests.csproj, Tests/UnitTests/GrainStateTests.cs, Tests/UnitTests/UnitTests.csproj
Updating to Orleans 8.2.0 + some package upgrades.
Closes: #425
=> Update to Orleans 8.2.0

OrleansDashboard/Implementation/Grains/DashboardGrain.cs, OrleansDashboard/Implementation/Helpers/GrainStateHelper.cs, Tests/UnitTests/GrainStateTests.cs
Closes https://github.com/OrleansContrib/OrleansDashboard/issues/428
=> Avoid loading all types when collecting grain types
