OrleansContrib/OrleansDashboard

TestHost/Program.cs

The thread with client calls is created but doesn't seem to be started.

Call Thread.Start in TestHost

---

OrleansDashboard/OrleansDashboard.csproj
TestGrains/TestGrains.csproj
TestHost/TestHost.csproj

Update to Orleans 1.5.0

---

OrleansDashboard/Dashboard.cs
OrleansDashboard/OrleansDashboard.csproj
OrleansDashboard/SiloDispatcher.cs

As I said: I fixed a deadlock.

Deadlock fixed

---

OrleansDashboard/DashboardMiddleware.cs
OrleansDashboard/OrleansDashboard.csproj
OrleansDashboard/StatsPublisher.cs
TestHost/Program.cs

Hi, 
I found another deadlock :(

Another deadlock fixed

---

App/logstream/log-stream.jsx
OrleansDashboard/Index.html

Added log stream regex filter and fixed some styling

---

App/components/reminder-table.jsx

Last one for the day :)
This PR will show the StartAt field in the ReminderTime in the user's machine's local time instead of the server UTC time

reminders - show local time

---

App/index.jsx
OrleansDashboard/DashboardController.cs
OrleansDashboard/Index.html

The orleans dashboard should probably show its version somewhere, this info is available in Visual Studio by searching for the Nuget package, but this makes it more simple to know what version of the dashboard you have

add version API and display it next to theme buttons

---

OrleansDashboard/OrleansDashboard.csproj
OrleansDashboard/ServiceCollectionExtensions.cs

Register dashboard as framework

---

OrleansDashboard/DashboardCounters.cs
OrleansDashboard/History/TraceHistory.cs
PerformanceTests/Program.cs

```
Method | SiloCount | GrainTypeCount | GrainMethodCount | HistorySize |     Mean |     Error |    StdDev |
-------------------------------------- |---------- |--------------- |----------------- |------------ |---------:|----------:|----------:|
Test_QueryAll_TraceHistory |        10 |             50 |               10 |         100 | 52.65 ms | 1.3421 ms | 1.8371 ms |
Test_QuerySilo_TraceHistory |        10 |             50 |               10 |         100 | 18.20 ms | 0.1283 ms | 0.1200 ms |
Test_QueryGrain_TraceHistory |        10 |             50 |               10 |         100 | 12.22 ms | 0.0981 ms | 0.0766 ms |
Test_GroupByGrainAndSilo_TraceHistory |        10 |             50 |               10 |         100 | 84.89 ms | 1.3049 ms | 1.0188 ms |
```

performance improvements to history

---

OrleansDashboard/DashboardTelemetryProducer.cs
OrleansDashboard/ServiceCollectionExtensions.cs

fix for #164

---

OrleansDashboard/GrainProfiler.cs

fixed exception logging in GrainProfiler

---

OrleansDashboard/Metrics/GrainProfilerFilter.cs

error recording results for grain (IIncomingGrainCallContext.ImplementationMethod )

 error recording results for grain

---

OrleansDashboard.Client/Model/DashboardCounters.cs
OrleansDashboard.Client/Model/GrainTraceEntry.cs
OrleansDashboard.Client/Model/History/GrainMethodAggregate.cs
OrleansDashboard/Metrics/History/GrainTraceEntryEqualityComparer.cs
OrleansDashboard/Metrics/History/TraceHistory.cs

* Fixes #255 
I have also removed the equality implementation from the grain trace entry and put them into a custom equality comparer. The grain trace entry has ~10 fields or so and which fields to use for equality depends on the use case and is an implementation detail of the class that uses it.

Fixes #255

---

Directory.Build.props
OrleansDashboard/OrleansDashboard.csproj
Tests/TestHosts/TestHostCohosted2/Properties/launchSettings.json
Tests/UnitTests/UnitTests.csproj

Updated to 3.0.0

---

Tests/TestHosts/TestHostMinimalApi/Program.cs
Tests/TestHosts/TestHostMinimalApi/TestHostMinimalApi.csproj

This is a TestHost that uses new dotnet 6 minimal api features.

Added a minimal api sample

---

OrleansDashboard/DashboardMiddleware.cs
OrleansDashboard/Implementation/TraceWriter.cs

Potentially fixes #319 
I've not reproduced the reported issue and instead assumed that the issue is related due to synchronous flushing. Nonetheless, this change can only add benefits.

Implement IAsyncDisposable on TraceWriter instead

---

OrleansDashboard.Core/ISiloGrain.cs
OrleansDashboard.Core/Metrics/GrainProfiler.cs
OrleansDashboard.Core/Metrics/GrainProfilerExtensions.cs
OrleansDashboard.Core/Metrics/GrainProfilerOptions.cs
OrleansDashboard.Core/Metrics/IGrainProfiler.cs
OrleansDashboard.EmbeddedAssets/OrleansDashboard.EmbeddedAssets.csproj
OrleansDashboard/Implementation/GrainProfilerFilter.cs
OrleansDashboard/Implementation/Grains/DashboardGrain.cs
OrleansDashboard/Implementation/Grains/SiloGrain.cs
OrleansDashboard/Implementation/LocalPlacementDirector.cs
OrleansDashboard/Implementation/LocalPlacementStrategy.cs
OrleansDashboard/ServiceCollectionExtensions.cs
Tests/TestHosts/TestHostCohosted2/Program.cs
Tests/TestHosts/TestHostCohosted2/TestHostCohosted2.csproj

Only track on demand.

---

OrleansDashboard.Core/Metrics/TypeFormatting/TypeFormatter.cs
OrleansDashboard/Implementation/GrainProfilerFilter.cs
OrleansDashboard/Implementation/Grains/DashboardGrain.cs
OrleansDashboard/ServiceCollectionExtensions.cs
Tests/UnitTests/TypeFormatterTests.cs

* Fix for type formatter. Closes #365
* Add reminder name into grain profiler. Closes #364
* Remove old method formatter signature.

Just a few fixes:

---

.gitignore
App/grains/grain-details.jsx
OrleansDashboard.Core/DashboardClient.cs
OrleansDashboard.Core/IDashboardClient.cs
OrleansDashboard.Core/IDashboardGrain.cs
OrleansDashboard/DashboardMiddleware.cs
OrleansDashboard/Implementation/Grains/DashboardGrain.cs

Fix dashboard client

---

OrleansDashboard/Dashboard.cs
Tests/TestHosts/TestHost/Program.cs
Tests/TestHosts/TestHostCohosted2/Properties/launchSettings.json

Hello, the EmbeddedAssetProvider not working, the service collection of host is recriated on Dashboard and the referency is losted.

OrleansDashboard.EmbeddedAssets not working.

---

OrleansDashboard.Core/OrleansDashboard.Core.csproj
OrleansDashboard/OrleansDashboard.csproj
Tests/PerformanceTests/PerformanceTests.csproj
Tests/TestGrains/TestGrains.csproj
Tests/TestHosts/TestHost/TestHost.csproj
Tests/TestHosts/TestHostCohosted2/TestHostCohosted2.csproj
Tests/TestHosts/TestHostSeparate/TestHostSeparate.csproj
Tests/UnitTests/UnitTests.csproj

Just a quick PR to upgrade all Nuget packages - I'm thinking this _should_ resolve #402.

Upgrading nuget packages

---

OrleansDashboard/BasicAuthMiddleware.cs

I've added some improvement related to string allocations and working with `StringValues` object.

Refactor BasicAuthMiddleware.cs to use spans and file scoped namespaces.

---

OrleansDashboard/Implementation/Grains/DashboardGrain.cs
OrleansDashboard/Implementation/Helpers/GrainStateHelper.cs

Tiny change following #430, the method doesn't seem to be useful being in the helper class, and the other method is already inlined.

Minor refactoring atop of #430

---

OrleansDashboard/Implementation/Grains/DashboardGrain.cs

fix: remove unused call to GetDetailedGrainStatistics #437
